# -*- coding: utf-8 -*-
"""Untitled8.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRvtRHpPEULtfDNbReka_Ven-75zhUgw
"""

a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
c=a+b
print(c)

